### PR TITLE
Warn if webroot is or starts with a port number

### PR DESCRIPTION
**Pull request by buchdag**
As discussed in #51 

Just changed the regexp to match 1-65535 rather than 0-99999.

### CODE REVIEW

**Comment by buchdag** [comment]
On a side note I have no idea why I end up with those bogus commits when I merge upstream changes, I've always been following [github instructions](https://help.github.com/articles/syncing-a-fork/) to do this and until recently it worked as intended, as in not producing `Merge remote-tracking branch 'upstream/master'` commits and making previous upstream commits appears on PR.

**Comment by zenhack** [comment]
I ended up just pushing a version of this myself; I wanted some tests and was a bit dissatisfied with the regex, and decided it was easiest to just do it myself, rather than play ping pong. Nonetheless, thanks for the patch and all of the work you're putting in. I'm going to close this though.

Re: the bogus  commits, it's not immediately obvious to me what's going on, but:

1. If you don't think it should need a merge commit, pass `--ff-only`; that way it will just error if you're wrong.
2. If you do have local changes, doing a rebase, rather than a merge, can result in cleaner history.
3. Usually when I'm starting out on a feature branch, I just do: `git checkout upstream/master -b my-feature`; this will start you out on a new branch that's at the same commit as the upstream master -- no need to mess with merging things back in.

**Comment by buchdag** [comment]
No problem, that's way cleaner without an ugly multi line regexp, wasn't fond of that either.

Thanks for the git tips !

**Comment by zenhack** [comment]
Yeah, you can only push regexes so far. And you're welcome!

**Pull request closed without merging**
