### PR TITLE
Zenhack/custom path external.sh

### PR DESCRIPTION
**Pull request by meeuw**

### CODE REVIEW

**Comment by zenhack** [comment]
My understanding of what this does:

1. Make it possible to specify extra flags per IOPlugin.
2. Add `--script` argument that specifies an alternate path to `external.sh`.

Re: (1) I think a simpler way to do this is to just have an optional method on IOPlugin that takes the parser and manipulates it; there's a bit too much machinery in this pr for my taste. Also, if we're going to allow the script to have other names, we might want to rename the plugin, since `external.sh` won't always be the name of the file.

I actually think the whole IOPlugin mechanism is a bit over-engineered as is, and the docs from a user standpointn are confusing. But exactly what to do about that is something I need to think about a bit.

**Comment by zenhack** [comment]
Ah, I noticed that the first commit is actually part of #41, so really this pr is just (2)

**Comment by meeuw** [comment]
"I actually think the whole IOPlugin mechanism is a bit over-engineered as is, and the docs from a user standpointn are confusing. But exactly what to do about that is something I need to think about a bit."

Completely true; I've created this PR mostly so that kuba might accept this.

**Comment by zenhack** [comment]
I'm going to go ahead and close this and the other prs you've submitted. Reason: IOPlugin doesn't need to be more complex, and supporting more mechanisms is an explicit non-goal of simp_le (so the dns patch isn't really wanted).

**Comment by meeuw** [comment]
You're right, no problem.

**Pull request closed without merging**
