### PR TITLE
Upgrade ACME to 1.2

### PR DESCRIPTION
**Pull request by buchdag**
The usual chore.

### CODE REVIEW

**Comment by zenhack** [comment]
Hm, do we actually need to bump the version here? we haven't made any changes and the existing constraint will accept newer versions.

(we should probably add a `<2.0` constraint; I thought I'd done that...)

**Comment by buchdag** [comment]
I don't really get why we switched from having a new tagged release when we bumped ACME minor version number to tagged release on ACME major version number in the first place.

TBH that's quite a bit annoying as it forces me to do a manual rebuild of `jrcs/letsencrypt-nginx-proxy-companion` images if I want to update the ACME minor version used by the image's `simp_le`, without any corresponding commit to track the change.

**Comment by zenhack** [comment]
The switch is because, per semver, 1.x marks the start of a stable API (I'm assuming acme is intends to follow semver, as it's recommended for python packages generally. but maybe we should check). 

Previously we had to track individual versions because there was no compatibility guarantee from one to the next. Semver requires that a breaking change wrt the 1.x series should see a major version bump, so we should have to tweak the bounds much less often now.

Re: the docker image, perhaps you could commit the output of `pip freeze`, rather than just recording the simp_le version in a script? This would have the advantage of making things more reproducible generally.

**Comment by buchdag** [comment]
Okay, the semantic versioning arguments make sense.

Using the output of `pip freeze` is a possibility but it will be a bit less convenient than just bumping a version number. How would you do this if you had to ? Using a virtualenv on a local machine ?

**Comment by zenhack** [comment]
Yeah, I'd probably use a local venv to generate it.

**Comment by buchdag** [comment]
So, `acme>=1.3 <2.0` and be done with it ?

**Comment by zenhack** [comment]
SGTM.

Quoting Nicolas Duchon (2020-03-05 08:32:05)

**Pull request merged**
